//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLizard.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TutorLizard.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Administracyjny.
        /// </summary>
        public static string AdminPanelMenu {
            get {
                return ResourceManager.GetString("AdminPanelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona startowa.
        /// </summary>
        public static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LoginMenu {
            get {
                return ResourceManager.GetString("LoginMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string LogoutMenu {
            get {
                return ResourceManager.GetString("LogoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string RegisterMenu {
            get {
                return ResourceManager.GetString("RegisterMenu", resourceCulture);
            }
        }
    }
}
