//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLizard.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TutorLizard.Web.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptuj.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptacja:.
        /// </summary>
        public static string Acceptance {
            get {
                return ResourceManager.GetString("Acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły ogłoszenia.
        /// </summary>
        public static string AdDetails {
            get {
                return ResourceManager.GetString("AdDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj termin.
        /// </summary>
        public static string AddScheduleItem {
            get {
                return ResourceManager.GetString("AddScheduleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Administracyjny.
        /// </summary>
        public static string AdminPanelMenu {
            get {
                return ResourceManager.GetString("AdminPanelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogłoszenie.
        /// </summary>
        public static string Advert {
            get {
                return ResourceManager.GetString("Advert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot ogłoszenia.
        /// </summary>
        public static string AdvertSubject {
            get {
                return ResourceManager.GetString("AdvertSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł ogłoszenia.
        /// </summary>
        public static string AdvertTitle {
            get {
                return ResourceManager.GetString("AdvertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne Terminy.
        /// </summary>
        public static string AvailableDates {
            get {
                return ResourceManager.GetString("AvailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj akceptację.
        /// </summary>
        public static string CancelAcceptation {
            get {
                return ResourceManager.GetString("CancelAcceptation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kategorii.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona startowa.
        /// </summary>
        public static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauczanie zdalne.
        /// </summary>
        public static string IsRemote {
            get {
                return ResourceManager.GetString("IsRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LoginMenu {
            get {
                return ResourceManager.GetString("LoginMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string LogoutMenu {
            get {
                return ResourceManager.GetString("LogoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zgłoszeń.
        /// </summary>
        public static string NoRequests {
            get {
                return ResourceManager.GetString("NoRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauczyciel.
        /// </summary>
        public static string PostedBy {
            get {
                return ResourceManager.GetString("PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string RegisterMenu {
            get {
                return ResourceManager.GetString("RegisterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzuć.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdalne.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość zwrotna.
        /// </summary>
        public static string ReplyMessage {
            get {
                return ResourceManager.GetString("ReplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaakceptowane.
        /// </summary>
        public static string RequestAccepted {
            get {
                return ResourceManager.GetString("RequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoszenie nie może zostać zaakceptowane.
        /// </summary>
        public static string RequestCannotBeAccepted {
            get {
                return ResourceManager.GetString("RequestCannotBeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wysłania.
        /// </summary>
        public static string RequestCreationDate {
            get {
                return ResourceManager.GetString("RequestCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłane.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaakceptowane.
        /// </summary>
        public static string RequestIsAccepted {
            get {
                return ResourceManager.GetString("RequestIsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezaakceptowane.
        /// </summary>
        public static string RequestIsRejected {
            get {
                return ResourceManager.GetString("RequestIsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja wiadomość.
        /// </summary>
        public static string RequestMessage {
            get {
                return ResourceManager.GetString("RequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wysłano.
        /// </summary>
        public static string RequestNotSent {
            get {
                return ResourceManager.GetString("RequestNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekujące.
        /// </summary>
        public static string RequestPending {
            get {
                return ResourceManager.GetString("RequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzucone.
        /// </summary>
        public static string RequestRejected {
            get {
                return ResourceManager.GetString("RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status zgłoszenia.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź nauczyciela.
        /// </summary>
        public static string RequestTutorResponse {
            get {
                return ResourceManager.GetString("RequestTutorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data przeglądu.
        /// </summary>
        public static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij zgłoszenie.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz się.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość od ucznia.
        /// </summary>
        public static string StudentMessage {
            get {
                return ResourceManager.GetString("StudentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tematyka.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauczyciel zaakceptował Twoje zgłoszenie.
        /// </summary>
        public static string TutorHasAcceptedRequest {
            get {
                return ResourceManager.GetString("TutorHasAcceptedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauczyciel nie zaakceptował Twojego zgłoszenia.
        /// </summary>
        public static string TutorHasRejectedRequest {
            get {
                return ResourceManager.GetString("TutorHasRejectedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje zgłoszenie.
        /// </summary>
        public static string YourRequest {
            get {
                return ResourceManager.GetString("YourRequest", resourceCulture);
            }
        }
    }
}
