//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLizard.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tutor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tutor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TutorLizard.Web.Resources.Tutor", typeof(Tutor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj ogłoszenie.
        /// </summary>
        public static string AddAd {
            get {
                return ResourceManager.GetString("AddAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj ogłoszenie.
        /// </summary>
        public static string AddAdvertisement {
            get {
                return ResourceManager.GetString("AddAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj termin.
        /// </summary>
        public static string AddScheduleItem {
            get {
                return ResourceManager.GetString("AddScheduleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id ogłoszenia.
        /// </summary>
        public static string AdId {
            get {
                return ResourceManager.GetString("AdId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie zgłoszenia.
        /// </summary>
        public static string AllAdRequests {
            get {
                return ResourceManager.GetString("AllAdRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje ogłoszenia.
        /// </summary>
        public static string AllAds {
            get {
                return ResourceManager.GetString("AllAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekujące  zgłoszenia.
        /// </summary>
        public static string AllPendingRequests {
            get {
                return ResourceManager.GetString("AllPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj wszystkie zgłoszenia.
        /// </summary>
        public static string BrowsAllAdRequests {
            get {
                return ResourceManager.GetString("BrowsAllAdRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj niezaakceptowane zgłoszenia.
        /// </summary>
        public static string BrowsePendingAdRequests {
            get {
                return ResourceManager.GetString("BrowsePendingAdRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id kategorii.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauczanie zdalne.
        /// </summary>
        public static string IsRemote {
            get {
                return ResourceManager.GetString("IsRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe ogłoszenie.
        /// </summary>
        public static string NewAd {
            get {
                return ResourceManager.GetString("NewAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy termin.
        /// </summary>
        public static string NewScheduleItem {
            get {
                return ResourceManager.GetString("NewScheduleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcjonalność nauczyciela.
        /// </summary>
        public static string TutorFunc {
            get {
                return ResourceManager.GetString("TutorFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj swoje ogłoszenia.
        /// </summary>
        public static string TutorsAdsLists {
            get {
                return ResourceManager.GetString("TutorsAdsLists", resourceCulture);
            }
        }
    }
}
